os: 'linux'
notifications:
  email: false
language: 'node_js'
node_js:
  - 12
branches:
  only:
    - gh-pages
    - /.*/
jobs:
  allow_failures:
    - install:
      - npm install eslint -g
    script:
      - eslint js/** tests/**
  include:
      before_install:
        - npm update
      install:
        - npm install jest -g
      script:
        - npm run test
      after_success:
        - codecov

    - install:
        - npm install eslint -g
      script:
        - eslint js/** tests/**
