os: 'linux'
notifications:
  email: false
language: 'node_js'
node_js:
  - 12
branches:
  only:
    - gh-pages
    - /.*/

before_script:
  - npm install

jobs:
  allow_failures:
    - script:
      - eslint js/** tests/**

  include:
      before_install:
        - npm update
      install:
        - npm install jest -g
      script:
        - npm run test
      after_success:
        - codecov

