os: 'linux'
language: node_js
  node_js:
    - '12'
branches:
  only:
    - gh-pages
    - /.*/
jobs:
  allow_failures:
    - install:
      - npm install eslint -g
    script:
      - eslint js/** tests/**
  include:
      cache:
        directories:
          - node_modules
      before_install:
        - npm update
      install:
        - npm install -g jest
      script:
        - npm run test
      after_success:
        - codecov

    - install:
        - npm install eslint -g
      script:
        - eslint js/** tests/**
